project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  back-to-top-navigation: true
  cookie-consent:
    type: express
    style: interstitial  
    palette: light 
  
  
  search:
    location: sidebar
    type: textbox
  # navbar:
  #   background: "#FFFF"
  #   foreground: dark
  #   right:
  #     - text: "Forum"
  #       href: https://twitter.com
  #   page-navigation: true
  #   title: "**DEVSTART**: gettting started with developmental science"
  #   tools:
  #     - icon: twitter
  #       href: https://twitter.com
  #     - icon: github
  #       href: https://github.com
    

  sidebar:
    style: "floating"
    # background: "#FFFFFF"
    border: true
    align: center
    
    # header: '# **DevStart**   
    # *gettting started with developmental science*'
    
    # title: "DevStart"
    logo: LOGO.png # IconB2.svg

    
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com
    
    
    contents:
      - index.qmd
      - section: "Getting started:"
        contents:
          - CONTENT/GettingStarted/GettingStartedWithPython.qmd
      - section: "Creating an experiment:"
        contents: 
          - CONTENT/GettingStarted/GettingStartedWithPsychopy.qmd
      - section: "Eye-tracking"
        contents: 
            - CONTENT/EyeTracking/Intro_eyetracking.qmd
            - CONTENT/EyeTracking/CreateAnEyetrackingExperiment.qmd
            - CONTENT/EyeTracking/I2MC_tutorial.qmd
          



  page-footer:
    center:  
      - href: https://github.com/realworlddatascience
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/
        icon: twitter
        aria-label: Twitter

format:
  html:
    toc: true
    toc-expand: 2    
    
    theme:
      light: bookup.scss
      dark: bookup_dark.scss

    mainfont: 'Arial'

    highlight-style: zenburn
    code-copy: true
    code-link: true
    code-overflow: wrap


editor: visual

