project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "DevStart"
  description: "DevStart is an online hands-on manual for anyone who is approaching developmental psychology and developmental cognitive neuroscience for the first time, from master's students and PhDs to postdocs."
  site-url: "https://tommasoghilardi.github.io/DevStart/"
  repo-url: "https://github.com/TommasoGhilardi/DevStart"
  image: "images/LOGO.png"
  google-analytics: "G-G5XSH1GLW7"
  
  # Cards
  open-graph:
    title: "DevStart"
    description: "Getting started with developmental science"
    image: "favicon.png"
  
  twitter-card: 
    title: "DevStart"
    card-style: summary
    description: "Language, stats, R"
    site: "@DevSciStart"
    image: "favicon.png"
  
  favicon: favicon.png



  # Utilities
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: true

  search:
    location: sidebar
    type: textbox

  sidebar:
    title: " "
    style: "floating"
    border: true
    align: center
    logo: "images/LOGO.png"

    tools:
      - icon: twitter
        href: https://x.com/DevSciStart
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/TommasoGhilardi/DevStart
          - text: Report a Bug
            url:  https://github.com/TommasoGhilardi/DevStart/issues
    
    contents:
      - index.qmd
      - section: "Getting started:"
        contents:
          - CONTENT/GettingStarted/GettingStartedWithPython.qmd
          - CONTENT/GettingStarted/GettingStartedWithPsychopy.qmd

      - section: "Creating an experiment:"
        href: CONTENT/GettingStarted/CreateYourFirstParadigm.qmd
        contents:
          - CONTENT/GettingStarted/CreateYourFirstParadigm.qmd
      - section: "Eye-tracking"
        href: CONTENT/EyeTracking/Intro_eyetracking.qmd
        contents: 
          - CONTENT/EyeTracking/Intro_eyetracking.qmd
          - CONTENT/EyeTracking/CreateAnEyetrackingExperiment.qmd
          - CONTENT/EyeTracking/EyetrackingCalibration.qmd
          - CONTENT/EyeTracking/I2MC_tutorial.qmd
          - CONTENT/EyeTracking/FromFixationsToData.qmd
      - section: "Workshops"
        contents:
          #- CONTENT/Workshops/BCCCD2024.qmd
          - CONTENT/Workshops/GAP_2024.qmd



  page-footer:
    center:  
      - href: https://github.com/TommasoGhilardi/DevStart
        icon: github
        aria-label: GitHub
      - href: https://x.com/DevSciStart
        icon: twitter
        aria-label: Twitter


format:
  html:

    toc: true
    toc-expand: 4    
    
    theme:
      light: bookup.scss
      # dark:  bookup_dark.scss

    mainfont: 'Arial'

    
    # Code variables
    code-fold: false
    code-copy: true
    code-link: true
    code-overflow: scroll
    code-tools:
      source: true
      toggle: true
      caption: none
    highlight-style: zenburn

    code-block-border-left: "#00B3B3"
editor: visual

