project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  site-url: "https://tommasoghilardi.github.io/DevStart/"
  google-analytics: "G-G5XSH1GLW7"
  twitter-card: true
  open-graph: true
  
  cookie-consent:
    type: implied
    style: simple    

  back-to-top-navigation: true

  search:
    location: sidebar
    type: textbox
  # navbar:
  #   background: "#FFFF"
  #   foreground: dark
  #   right:
  #     - text: "Forum"
  #       href: https://twitter.com
  #   page-navigation: true
  #   title: "**DEVSTART**: gettting started with developmental science"
  #   tools:
  #     - icon: twitter
  #       href: https://twitter.com
  #     - icon: github
  #       href: https://github.com
    

  sidebar:
    style: "floating"
    border: true
    align: center
    

    
    # title: "DevStart"
    logo: images/LOGO.png # IconB2.svg

    
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com/TommasoGhilardi/DevStart
    
    
    contents:
      - index.qmd
      - section: "Getting started:"
        contents:
          - CONTENT/GettingStarted/GettingStartedWithPython.qmd
      - section: "Creating an experiment:"
        contents: 
          - CONTENT/GettingStarted/GettingStartedWithPsychopy.qmd
      - section: "Eye-tracking"
        contents: 
          - CONTENT/EyeTracking/Intro_eyetracking.qmd
          - CONTENT/EyeTracking/CreateAnEyetrackingExperiment.qmd
          - CONTENT/EyeTracking/I2MC_tutorial.qmd
          - CONTENT/EyeTracking/CreateAnEyetrackingExperiment.qmd




  page-footer:
    center:  
      - href: https://github.com/TommasoGhilardi/DevStart
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/
        icon: twitter
        aria-label: Twitter

format:
  html:
    toc: true
    toc-expand: 2    
    
    theme:
      light: bookup.scss
      dark:  bookup_dark.scss

    mainfont: 'Arial'


    # Code variables
    code-fold: false
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-tools:
      source: true
      toggle: true
      caption: none
      
    highlight-style: zenburn

    code-block-border-left: "#00B3B3"
editor: visual

