---
title: "BCCCD2024"

execute:
  eval: false
title-meta: "BCCCD2024"
author-meta: Tommaso Ghilardi
description-meta: "Data and resource for the workshop at BCCCD 2024"
keywords: "PsychoPy, Python, eye-tracking, tobii, tobii_research, experimental psychology, tutorial, experiment, DevStart, developmental science, workshop"
---

Hello hello!!! This page has been created to provide support and resources for the tutorial and we presented at BCCCD24.

# What will you learn?

This workshop will focus on using Python to run and analyze an eye-tracking study.

We will focus on:

-   How to implement eye-tracking designs in Python

-   How to interact with an eye-tracker via Python

-   How to extract and visualize meaningful eye-tracking measures from the raw data

# What will you need?

## Software

In this tutorial, our primary tool will be Python!! We recommend installing it via [Miniconda](https://docs.conda.io/projects/miniconda/en/latest/). Our interaction with Python will primarily be through the Spyder IDE. You're free to use any IDE of your choice, but if you'd like to follow along more smoothly, we suggest checking out our guide on how to install both Miniconda and Spyder: [Getting started with Python](/CONTENT/GettingStarted/GettingStartedWithPython.qmd).

Besides Python, we'll also be utilizing Psychopy! Psychopy is an awesome set of packages and functions designed for conducting psychological experiments. It's available as a standalone software or can be installed as a Python package.

Based on our experience, we find it more advantageous to use Psychopy as a Python package due to its increased flexibility. We provide this `<a href="/resources/psychopy.yml" download>anaconda environment</a>`{=html} to easily create a virtual environment with both python, psychopy and all the libraries that we will need. You can find details on how to install a conda environment on this page: [Getting started with Psychopy](/CONTENT/GettingStarted/GettingStartedWithPsychopy.qmd)

## Files

In our workshop we will create a cool eye-tracking study, collect the data and analyze them. To make everything smoother we provide [HERE](/resources/Workshops/BCCCD2024.zip) the stimuli and the data that we will use for the workshop.

# Q&A

This section is dedicated to the questions and answers that arise during the workshop. We will document the most pertinent and intriguing ones here for future reference and to assist anyone who might have similar queries.

**So... don't hesitate to ask a multitude of questions!!!**
